name: Exort
version: "${version}"
main: com.zxcmc.exort.core.ExortPlugin
description: "${description}"
api-version: "1.21"
authors: ["phantomfighterxx"]
libraries:
  - org.xerial:sqlite-jdbc:3.45.3.0
dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true
    Nexo:
      load: BEFORE
      required: false
      join-classpath: false
